"""Write publication tables from regraded saved runs; no network or inference."""
import json
from pathlib import Path
from analyze_followup import analyze
def label(model):return model.split("/")[-1].split("@")[0].replace("-2026-03-17", "")

HERE=Path(__file__).resolve().parent
ROOT=HERE.parent

def main():
 d=analyze();p=d['pooled'];e=p['exp1']['1']['all']
 rows=['| Model | Clean | Confident comment | Wrong target: clean → comment | Different code | Same code | Repeat changes |',
       '|---|---:|---:|---:|---:|---:|---:|']
 f=lambda g:f'{g["correct"]}/{g["answered"]}'
 for model in d['included_first_run_models']:
  r=d['models'][model];a=r['exp1']['1']['all'];s=r['stability']['all']
  repeat=f'{s["changed"]}/{s["comparable_valid_answers"]}' if s['comparable_valid_answers'] else 'Not repeated'
  rows.append(f'| {label(model)} | {f(a["L0"])} | {f(a["L2"])} | {a["L0"]["followed"]} → {a["L2"]["followed"]} | {f(r["exp2"]["different"])} | {f(r["exp2"]["same"])} | {repeat} |')
 table='\n'.join(rows)
 costs=[]
 for path in sorted((HERE/'runs').rglob('*.result.json')):
  r=json.loads(path.read_text());info=r.get('agent_info',{}).get('model_info',{})
  costs.append(dict(path=str(path.relative_to(HERE)),model=info.get('name'),cost_usd=r.get('agent_result',{}).get('cost_usd'),started_at=r.get('started_at'),finished_at=r.get('finished_at')))
 unique={(r['model'],r['started_at'],r['finished_at']):r for r in costs}
 known=[r['cost_usd'] for r in unique.values() if r['cost_usd'] is not None]
 manifest=dict(sdk_runs=list(unique.values()),total_recorded_sdk_cost_usd=sum(known),missing_cost_records=len(unique)-len(known),note='Includes initialization and the extra expansion in the mislabeled nano run; deduplicates copied SDK result records. Quota also reflects active reservations.')
 (HERE/'cost_actual.json').write_text(json.dumps(manifest,indent=2)+'\n')
 summary=d['headline']+'\n\n'+table+'\n\n'
 summary+='Accuracy denominators are answered prompts; full first runs are required for inclusion. Repeat changes compare verdict plus ID, excluding unreadable/API-error pairs. The original test and follow-up use distinct datasets.\n\n'
 summary+='[Full rates and Wilson 95% intervals](followup/results_summary.md) · [Raw responses](followup/runs/) · [Design and audit](followup/README.md) · [Public follow-up task](https://www.kaggle.com/benchmarks/tasks/jashanpreetkaur24/zombiebench-followup)\n'
 start='<!-- FOLLOWUP RESULTS START -->';end='<!-- FOLLOWUP RESULTS END -->'
 readme=(ROOT/'README.md').read_text()
 block=start+'\n## Follow-up experiment\n\n'+summary+end+'\n\n'
 if start in readme:readme=readme[:readme.index(start)]+block+readme[readme.index(end)+len(end):].lstrip('\n')
 else:readme=readme.replace('## Key findings\n',block+'## Key findings\n',1)
 readme=readme.replace('There was no control run without the note, so this does not establish that the\nnote caused those answers.', 'The original study had no clean control, so that observation alone does not establish causation.\nThe controlled follow-up above tests standardized comment insertions separately.')
 (ROOT/'README.md').write_text(readme)
 notes=(ROOT/'NOTES.md').read_text();heading='## Phase 9: Controlled follow-up (2026-10-09)'
 if heading in notes:notes=notes[:notes.index(heading)].rstrip()+'\n'
 details='\n\n'+heading+'\n\n'+summary.replace('(followup/', '(followup/')
 details+='\nAll follow-up claims are generated by `followup/analyze_followup.py` from archived replies and checked against their prompt hashes and the frozen grader. `followup/run_adjustments.json` records the actual-model correction without changing raw files. Sonnet 4.5 was unavailable and was not substituted; the platform initialization model is excluded from planned-model pools.\n'
 details+=f'\nSaved SDK result files report ${manifest["total_recorded_sdk_cost_usd"]:.6f} total inference cost, including initialization and excluded extra expansion calls. This is recorded cost, not a quote for future runs.\n'
 details+='\nThe original audit counts were recorded in the historical build log but lacked archived raw audit answers; the revised article does not present those counts as independently reverified. Follow-up blind-audit inputs and answers are archived.\n'
 details+='\nWilson intervals are descriptive; shared cases and models create dependence. The comment contrast estimates the effect of the entire inserted comment. L1 versus L3 changes confidence and claimed authority together. The matched expansion uses repeated synthetic scaffolds and is not calibrated to expert difficulty.\n'
 (ROOT/'NOTES.md').write_text(notes+details)
 (HERE/'model_results.md').write_text(table+'\n')
 print('Updated README.md, NOTES.md, model_results.md and cost_actual.json from saved files.')

if __name__=='__main__':main()
